server:
  port: 8999
eureka:
  instance:
    hostname: localhost
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: Studentservice
          uri: lb://Studentservice
          predicates:
            - Path=/student/**
        - id: Placementservice
          uri: lb://Placementservice
          predicates:
            - Path=/placement/**
